전처리된 "3. major_detail.csv" 를 Contents 기반으로 군집화를 시도해 보았다.

최종적으로 사용되지는 않았으나 꽤나 괜찮은 정확도를 보임.

In [17]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv('3. major_detail.csv')
df

Unnamed: 0              전공명  \
0             0             생화학과   
1             1  특수교육학과 (특수, 교육)   
2             2           도시계획학과   
3             3            도시공학과   
4             4          목조형가구학과   
..          ...              ...   
510         510            환경관리과   
511         511            환경교육과   
512         512           환경조각학과   
513         513            환경화학과   
514         514             회화학과   

                                                   키워드  
0    생화학, 단백질, 생명, 현상, 세포, 생합성, 생체, 기능, 고분자, 대사, 정제...  
1    특수교육, 교육, 특수, 학급, 사, 학생, 정신, 장애, 대상자, 교육과정, 발달...  
2    도시, 계획, 수립, 지역, 측량, 개발, 분석, 땅, 공간, 인간, 부동산, 조경...  
3    도시, 도시공학, 계획, 건설, 교통, 공간, 부, 토지, 설계, 개발, 발전, 이...  
4    가구, 조형, 디자인, 입체, 표현, 디자이너, 목, 현대, 목공, 공간, 미, 사...  
..                                                 ...  
510  수질, 오염, 대기, 산업기사, 물질, 처리, 대기 오염, 폐기물, 분석, 미생물,...  
511  교육, 환경오염, 법, 오염, 교사, 실제, 생태계, 환경영향평가, 단위, 대기, ...  
512  조각, 조형, 바탕, 현대, 표현, 디자인, 공간, 인체, 순수, 인간, 작품, 창...  
513  산업기사, 화학, 오염, 법, 물질, 공정, 제조, 고분자, 발생, 수질, 가스, ...  
514  회화, 미술, 조형, 한국, 흐름, 시대, 입체, 미술사, 양식, 표현, 현대, 사...  

[515 rows x 3 columns]

In [19]:
data = df[['전공명', '키워드']]
data

전공명                                                키워드
0               생화학과  생화학, 단백질, 생명, 현상, 세포, 생합성, 생체, 기능, 고분자, 대사, 정제...
1    특수교육학과 (특수, 교육)  특수교육, 교육, 특수, 학급, 사, 학생, 정신, 장애, 대상자, 교육과정, 발달...
2             도시계획학과  도시, 계획, 수립, 지역, 측량, 개발, 분석, 땅, 공간, 인간, 부동산, 조경...
3              도시공학과  도시, 도시공학, 계획, 건설, 교통, 공간, 부, 토지, 설계, 개발, 발전, 이...
4            목조형가구학과  가구, 조형, 디자인, 입체, 표현, 디자이너, 목, 현대, 목공, 공간, 미, 사...
..               ...                                                ...
510            환경관리과  수질, 오염, 대기, 산업기사, 물질, 처리, 대기 오염, 폐기물, 분석, 미생물,...
511            환경교육과  교육, 환경오염, 법, 오염, 교사, 실제, 생태계, 환경영향평가, 단위, 대기, ...
512           환경조각학과  조각, 조형, 바탕, 현대, 표현, 디자인, 공간, 인체, 순수, 인간, 작품, 창...
513            환경화학과  산업기사, 화학, 오염, 법, 물질, 공정, 제조, 고분자, 발생, 수질, 가스, ...
514             회화학과  회화, 미술, 조형, 한국, 흐름, 시대, 입체, 미술사, 양식, 표현, 현대, 사...

[515 rows x 2 columns]

In [24]:
for i in range(len(data['전공명'])):
    data['키워드'][i] = data['키워드'][i].replace(', ', ' ')
data

C:\Users\KOH_AI\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3331: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)


전공명                                                키워드
0               생화학과  생화학 단백질 생명 현상 세포 생합성 생체 기능 고분자 대사 정제 역할 물질 반응 ...
1    특수교육학과 (특수, 교육)  특수교육 교육 특수 학급 사 학생 정신 장애 대상자 교육과정 발달 적용 정의 아동 ...
2             도시계획학과  도시 계획 수립 지역 측량 개발 분석 땅 공간 인간 부동산 조경 합리 계획학 관계 ...
3              도시공학과   도시 도시공학 계획 건설 교통 공간 부 토지 설계 개발 발전 이용 지역 미래 사람 토목
4            목조형가구학과      가구 조형 디자인 입체 표현 디자이너 목 현대 목공 공간 미 사용 기능 시각 기계
..               ...                                                ...
510            환경관리과       수질 오염 대기 산업기사 물질 처리 대기 오염 폐기물 분석 미생물 측정 환경오염
511            환경교육과       교육 환경오염 법 오염 교사 실제 생태계 환경영향평가 단위 대기 수질 화학 교과
512           환경조각학과  조각 조형 바탕 현대 표현 디자인 공간 인체 순수 인간 작품 창의 기획 수업 독창 ...
513            환경화학과  산업기사 화학 오염 법 물질 공정 제조 고분자 발생 수질 가스 분석 교육 자 생명 ...
514             회화학과  회화 미술 조형 한국 흐름 시대 입체 미술사 양식 표현 현대 사상 체계 학예사 서 ...

[515 rows x 2 columns]

In [25]:
stock = data


from sklearn.feature_extraction.text import TfidfVectorizer
# ngram_range=(1, 2) 는 단어를 1개 혹은 2개 연속으로 보겠다
tfidf_vec = TfidfVectorizer(ngram_range=(1, 2))
# ketwords 대신 ISSUE_CTNT사용
tfidf_matrix = tfidf_vec.fit_transform(stock['키워드'])
print(tfidf_vec.vocabulary_.items())
# 515은 종목의 개수, 336은 단어의 개수 -> 하나의 주식를 336개 열을 가진 벡터로 표현
print(tfidf_matrix.shape)

# action adventure fantasy
# adventure fantasy
# adventure
# fantasy

dict_items([('생화학', 3909), ('단백질', 1932), ('생명', 3793), ('현상', 8887), ('세포', 4211), ('생합성', 3906), ('생체', 3888), ('기능', 1608), ('고분자', 605), ('대사', 1960), ('정제', 6905), ('역할', 5140), ('물질', 2704), ('반응', 2874), ('화학', 9074), ('분자', 3421), ('생명체', 3824), ('핵산', 8781), ('구성', 1248), ('생물체', 3845), ('지질', 7479), ('효소', 9266), ('생화학 단백질', 3910), ('단백질 생명', 1934), ('생명 현상', 3810), ('현상 세포', 8904), ('세포 생합성', 4217), ('생합성 생체', 3907), ('생체 기능', 3889), ('기능 고분자', 1611), ('고분자 대사', 608), ('대사 정제', 1967), ('정제 역할', 6906), ('역할 물질', 5146), ('물질 반응', 2708), ('반응 화학', 2883), ('화학 분자', 9084), ('분자 생명체', 3423), ('생명체 핵산', 3825), ('핵산 구성', 8782), ('구성 생물체', 1264), ('생물체 지질', 3847), ('지질 효소', 7483), ('특수교육', 8218), ('교육', 1053), ('특수', 8209), ('학급', 8493), ('학생', 8528), ('정신', 6891), ('장애', 6502), ('대상자', 1974), ('교육과정', 1184), ('발달', 2892), ('적용', 6625), ('정의', 6900), ('아동', 4792), ('학교', 8489), ('치료', 7889), ('상담', 3730), ('심리', 4753), ('특수교육 교육', 8219), ('교육 특수', 1162), ('특수 학급', 8216), ('학급 학생', 84

In [26]:
# 유사도 행렬 (4803, 4803)
# 1, 1 (1번째 영화와 1번재 영화의 유사도)
# 1, 1 / 1, 2 / .... / 1, 4803 -> 1번째 영화와 1~4803번재 영화의 유사도
# 2, 1 / 2, 2 / .... / 2, 4803 -> 2번째 영화와 1~4803번째 영화의 유사도
# ....
# 4803, 1 / 4803, 2 / .... / 4803, 4803 -> 4803번째 영화와 1~4803번째 영화의 유사도
from sklearn.metrics.pairwise import cosine_similarity

# 10개의 종목이랑 10개의 종목끼리 유사도를 구하겠다!
# 자신과의 유사도는 1
genres_similarity = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(genres_similarity)
# 유사도 값이 높은 영화의 제목
# 유사도 값이 높은 순으로 인덱스 값을 뽑아낸다
similar_index = np.argsort(-genres_similarity)
print(similar_index)

[[1.         0.         0.         ... 0.         0.06157796 0.        ]
 [0.         1.         0.         ... 0.         0.00459445 0.        ]
 [0.         0.         1.         ... 0.03001001 0.0080603  0.        ]
 ...
 [0.         0.         0.03001001 ... 1.         0.         0.05389797]
 [0.06157796 0.00459445 0.0080603  ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.05389797 0.         1.        ]]
[[  0 451 147 ... 177 200 514]
 [  1 115 332 ... 206 247 514]
 [  2 233 315 ... 195 190 514]
 ...
 [512  93 281 ... 206 218 257]
 [513  36 507 ... 248 269 514]
 [514 339 243 ... 192 157 257]]


In [41]:
genres_similarity[500]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01948302, 0.01876498, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01867929, 0.01984954, 0.        , 0.01679946, 0.        ,
       0.        , 0.01149788, 0.03883475, 0.02777805, 0.        ,
       0.02284478, 0.03022739, 0.        , 0.        , 0.03124417,
       0.        , 0.        , 0.        , 0.        , 0.     

In [44]:
# 사용자가 입력한 조의 인덱스 값을 찾아내고
# similar_index 에 기록된 유사한 영화 인덱스를 찾아내고
# 유사한 영화 인덱스를 토대로 영화 이름을 찾아내면 된다!
input_stock = input()

stock_index = stock[stock['전공명'] ==input_stock].index.values
print(stock_index)
similar_stock = similar_index[stock_index, :40]
print(similar_stock)
# 인덱스로 사용하기 위해서는 1차원으로 변형해줘야하기 때문
similar_stock_index = similar_stock.reshape(-1)
print(similar_stock_index)
print(stock.iloc[similar_stock_index])

print(genres_similarity[stock_index][[similar_stock_index]])

한문학과
[500]
[[500 143 459 127 414 506  62 335  77 344 139 138  78 502 234 423  93 126
  130  69 124  66 135 492 427 366  63 340 131  99 409 393 257 456 106  65
  450 137 475 224]]
[500 143 459 127 414 506  62 335  77 344 139 138  78 502 234 423  93 126
 130  69 124  66 135 492 427 366  63 340 131  99 409 393 257 456 106  65
 450 137 475 224]
                  전공명                                                키워드
500              한문학과  한문학 한문 우리나라 작품 한자 고전 중국 형성 전개 해독 선현 역사 문학 문 해석...
143             한문교육과       한문 교육 한문학 체계 교사 한국 작가 형성 중 중등학교 교과서 분석 한시 일반
459              인문학부  대 세계 한국 문학 주의 현대 근대 논리 철학 중심 21세기 고대 시대 역사 한국 ...
127           스토리텔링학과  스토리텔링 문학 매체 스토리 이야기 텔 군단 광고 홍보 사서 기반 연구소 국가 민간...
414           러시아어문학과  러시아 러시아어 문학 노어 무역 작가 비평 작품 민간 호텔 역사 관계 어문학 경제 ...
506            헝가리어학과                    헝가리어 헝가리 구비 역사 경험 내사 안 통역 일반 언어
62              기독교학과  기독교 신학 역사 계시 개별 종교 복음서 상담 학문 복지 문학 신약성경 성경 교리 ...
335    기술교육과 (기술, 교육)  교육 기계 공부 교사 에너지 교과 이용 측정 열역학 해석 전기 제품 공작기계 일반 ...


C:\Users\KOH_AI\anaconda3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  from ipykernel import kernelapp as app


IndexError: index 500 is out of bounds for axis 0 with size 1